version: '3.8'
services:
  console:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/opt
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - LAMBDA_DOCKER_NETWORK=localstacknetwork1
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=12345678
      - AWS_SECRET_ACCESS_KEY=12345678
    networks:
      - localstacknetwork1
    volumes:
      - "./.localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true

networks:
  localstacknetwork1:
    external: true
    name: localstacknetwork1